export const FETCH_CAR_NUMBER_PLATES_INIT = 'FETCH_CAR_NUMBER_PLATES_INIT';
export const FETCH_CAR_NUMBER_PLATES_START = 'FETCH_CAR_NUMBER_PLATES_START';
export const FETCH_CAR_NUMBER_PLATES_SUCCESS = 'FETCH_CAR_NUMBER_PLATES_SUCCESS';
export const FETCH_CAR_NUMBER_PLATES_FAIL = 'FETCH_CAR_NUMBER_PLATES_FAIL';

export const MODIFY_CAR_NUMBER_PLATE_INIT = 'MODIFY_CAR_NUMBER_PLATE_INIT';

export const FETCH_CAR_NUMBER_PLATE_START = 'FETCH_CAR_NUMBER_PLATE_START';
export const FETCH_CAR_NUMBER_PLATE_SUCCESS = 'FETCH_CAR_NUMBER_PLATE_SUCCESS';
export const FETCH_CAR_NUMBER_PLATE_FAIL = 'FETCH_CAR_NUMBER_PLATE_FAIL';

export const DELETE_CAR_NUMBER_PLATE_START = 'DELETE_CAR_NUMBER_PLATE_START';
export const DELETE_CAR_NUMBER_PLATE_SUCCESS = 'DELETE_CAR_NUMBER_PLATE_SUCCESS';
export const DELETE_CAR_NUMBER_PLATE_FAIL = 'DELETE_CAR_NUMBER_PLATE_FAIL';