export const FETCH_CAR_NUMBER_PLATES_INIT = 'FETCH_CAR_NUMBER_PLATES_INIT';
export const FETCH_CAR_NUMBER_PLATES_START = 'FETCH_CAR_NUMBER_PLATES_START';
export const FETCH_CAR_NUMBER_PLATES_SUCCESS = 'FETCH_CAR_NUMBER_PLATES_SUCCESS';
export const FETCH_CAR_NUMBER_PLATES_FAIL = 'FETCH_CAR_NUMBER_PLATES_FAIL';

export const FETCH_CAR_NUMBER_PLATE_START = 'FETCH_CAR_NUMBER_PLATE_START';
export const FETCH_CAR_NUMBER_PLATE_SUCCESS = 'FETCH_CAR_NUMBER_PLATE_SUCCESS';
export const FETCH_CAR_NUMBER_PLATE_FAIL = 'FETCH_CAR_NUMBER_PLATE_FAIL';

export const MODIFY_CAR_NUMBER_PLATE_INIT = 'MODIFY_CAR_NUMBER_PLATE_INIT';
export const MODIFY_CAR_NUMBER_PLATE_START = 'MODIFY_CAR_NUMBER_PLATE_START';
export const MODIFY_CAR_NUMBER_PLATE_SUCCESS = 'MODIFY_CAR_NUMBER_PLATE_SUCCESS';
export const MODIFY_CAR_NUMBER_PLATE_FAIL = 'MODIFY_CAR_NUMBER_PLATE_FAIL';

export const CREATE_CAR_NUMBER_PLATE_INIT = 'CREATE_CAR_NUMBER_PLATE_INIT';
export const CREATE_CAR_NUMBER_PLATE_START = 'CREATE_CAR_NUMBER_PLATE_START';
export const CREATE_CAR_NUMBER_PLATE_SUCCESS = 'CREATE_CAR_NUMBER_PLATE_SUCCESS';
export const CREATE_CAR_NUMBER_PLATE_FAIL = 'CREATE_CAR_NUMBER_PLATE_FAIL';